version: '2'
services:
  redis:
    image: "redis"
    ports:
     - "6379:6379"
    volumes:
     - C:\ArabicTutorials\redis:/data
  mongo:
    image: "mongo"
    ports:
     - "27017:27017"
    volumes:
     - C:\ArabicTutorials\mongo:/data/db